/********************************************************************************
** Form generated from reading UI file 'borg_backup_gui.ui'
**
** Created by: Qt User Interface Compiler version 5.11.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_BORG_BACKUP_GUI_H
#define UI_BORG_BACKUP_GUI_H

#include <QtCore/QLocale>
#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QListWidget>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QProgressBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTextBrowser>
#include <QtWidgets/QTimeEdit>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_BORG_BackUP_GUI
{
public:
    QAction *actionMount;
    QAction *actionUnmount;
    QAction *actionmore_Details;
    QAction *actionBackUP_NOW;
    QAction *actionExit;
    QAction *actionAbout;
    QAction *New;
    QAction *About_Menu;
    QAction *Exit;
    QAction *Create_a_new_BackUP_point_Menu;
    QAction *Mount_Menu;
    QAction *Unmount_Menu;
    QAction *Details_Menu;
    QAction *actionDelete;
    QAction *Schedule_Section_Menu;
    QAction *Delete_Section_Menu;
    QAction *Configuration_Menu;
    QAction *Borg_Homepage_Menu;
    QAction *Tutorial_Menu;
    QWidget *Main;
    QTabWidget *tabWidget;
    QWidget *BackUP;
    QLabel *Info_4;
    QProgressBar *progressBar_2;
    QLabel *Info_6;
    QLabel *label_3;
    QLabel *Info;
    QLabel *Info_5;
    QPushButton *Details;
    QPushButton *BackUP_NOW;
    QLabel *Info_2;
    QLabel *label;
    QProgressBar *progressBar;
    QProgressBar *progressBar_3;
    QLabel *Info_3;
    QLabel *label_2;
    QPushButton *Unmount;
    QPushButton *Mount;
    QPushButton *openMount;
    QWidget *Configuration;
    QLabel *pathInfo_5;
    QLabel *pathInfo_6;
    QLabel *pathInfo_7;
    QLabel *pathInfo_8;
    QLabel *pathInfo_9;
    QPushButton *Config_File;
    QLineEdit *pathInfo_2;
    QLineEdit *pathInfo;
    QLineEdit *pathInfo_3;
    QLineEdit *pathInfo_4;
    QLineEdit *pathInfo_10;
    QLineEdit *pathInfo_11;
    QLabel *pathInfo_12;
    QWidget *Delete;
    QListWidget *listWidget;
    QTextBrowser *textBrowser;
    QPushButton *DELETE;
    QLabel *Check_Delete;
    QLineEdit *Re_Check_Delete;
    QLabel *label_4;
    QFrame *frame;
    QWidget *Schedule;
    QTimeEdit *HH;
    QCheckBox *WD3;
    QCheckBox *WD4;
    QCheckBox *WD7;
    QCheckBox *WD5;
    QCheckBox *WD6;
    QCheckBox *WD2;
    QCheckBox *WD1;
    QLabel *label_5;
    QLabel *label_6;
    QFrame *line_4;
    QPushButton *Remove;
    QPushButton *AddChange;
    QComboBox *Time24AMPM;
    QLabel *label_7;
    QTimeEdit *mm;
    QLabel *label_8;
    QLabel *wait;
    QPushButton *BORG;
    QProgressBar *loadBAR_2;
    QProgressBar *loadBAR;
    QProgressBar *loadBAR_3;
    QMenuBar *menuBar;
    QMenu *menuFile;
    QMenu *menuHelp;
    QMenu *menuActions;

    void setupUi(QMainWindow *BORG_BackUP_GUI)
    {
        if (BORG_BackUP_GUI->objectName().isEmpty())
            BORG_BackUP_GUI->setObjectName(QStringLiteral("BORG_BackUP_GUI"));
        BORG_BackUP_GUI->resize(925, 383);
        actionMount = new QAction(BORG_BackUP_GUI);
        actionMount->setObjectName(QStringLiteral("actionMount"));
        actionUnmount = new QAction(BORG_BackUP_GUI);
        actionUnmount->setObjectName(QStringLiteral("actionUnmount"));
        actionmore_Details = new QAction(BORG_BackUP_GUI);
        actionmore_Details->setObjectName(QStringLiteral("actionmore_Details"));
        actionBackUP_NOW = new QAction(BORG_BackUP_GUI);
        actionBackUP_NOW->setObjectName(QStringLiteral("actionBackUP_NOW"));
        actionExit = new QAction(BORG_BackUP_GUI);
        actionExit->setObjectName(QStringLiteral("actionExit"));
        actionAbout = new QAction(BORG_BackUP_GUI);
        actionAbout->setObjectName(QStringLiteral("actionAbout"));
        New = new QAction(BORG_BackUP_GUI);
        New->setObjectName(QStringLiteral("New"));
        About_Menu = new QAction(BORG_BackUP_GUI);
        About_Menu->setObjectName(QStringLiteral("About_Menu"));
        Exit = new QAction(BORG_BackUP_GUI);
        Exit->setObjectName(QStringLiteral("Exit"));
        Create_a_new_BackUP_point_Menu = new QAction(BORG_BackUP_GUI);
        Create_a_new_BackUP_point_Menu->setObjectName(QStringLiteral("Create_a_new_BackUP_point_Menu"));
        Mount_Menu = new QAction(BORG_BackUP_GUI);
        Mount_Menu->setObjectName(QStringLiteral("Mount_Menu"));
        Unmount_Menu = new QAction(BORG_BackUP_GUI);
        Unmount_Menu->setObjectName(QStringLiteral("Unmount_Menu"));
        Details_Menu = new QAction(BORG_BackUP_GUI);
        Details_Menu->setObjectName(QStringLiteral("Details_Menu"));
        actionDelete = new QAction(BORG_BackUP_GUI);
        actionDelete->setObjectName(QStringLiteral("actionDelete"));
        Schedule_Section_Menu = new QAction(BORG_BackUP_GUI);
        Schedule_Section_Menu->setObjectName(QStringLiteral("Schedule_Section_Menu"));
        Delete_Section_Menu = new QAction(BORG_BackUP_GUI);
        Delete_Section_Menu->setObjectName(QStringLiteral("Delete_Section_Menu"));
        Configuration_Menu = new QAction(BORG_BackUP_GUI);
        Configuration_Menu->setObjectName(QStringLiteral("Configuration_Menu"));
        Borg_Homepage_Menu = new QAction(BORG_BackUP_GUI);
        Borg_Homepage_Menu->setObjectName(QStringLiteral("Borg_Homepage_Menu"));
        Tutorial_Menu = new QAction(BORG_BackUP_GUI);
        Tutorial_Menu->setObjectName(QStringLiteral("Tutorial_Menu"));
        Main = new QWidget(BORG_BackUP_GUI);
        Main->setObjectName(QStringLiteral("Main"));
        tabWidget = new QTabWidget(Main);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        tabWidget->setGeometry(QRect(10, 10, 905, 321));
        QFont font;
        font.setPointSize(8);
        font.setBold(true);
        font.setWeight(75);
        tabWidget->setFont(font);
        tabWidget->setLocale(QLocale(QLocale::English, QLocale::UnitedStates));
        BackUP = new QWidget();
        BackUP->setObjectName(QStringLiteral("BackUP"));
        Info_4 = new QLabel(BackUP);
        Info_4->setObjectName(QStringLiteral("Info_4"));
        Info_4->setGeometry(QRect(177, 36, 60, 30));
        QFont font1;
        font1.setFamily(QStringLiteral("Droid Sans Thai"));
        font1.setPointSize(8);
        font1.setBold(true);
        font1.setWeight(75);
        Info_4->setFont(font1);
        Info_4->setLayoutDirection(Qt::RightToLeft);
        Info_4->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        progressBar_2 = new QProgressBar(BackUP);
        progressBar_2->setObjectName(QStringLiteral("progressBar_2"));
        progressBar_2->setGeometry(QRect(10, 75, 880, 60));
        QFont font2;
        font2.setPointSize(12);
        font2.setBold(true);
        font2.setWeight(75);
        progressBar_2->setFont(font2);
        progressBar_2->setValue(0);
        Info_6 = new QLabel(BackUP);
        Info_6->setObjectName(QStringLiteral("Info_6"));
        Info_6->setGeometry(QRect(177, 166, 60, 30));
        Info_6->setFont(font1);
        Info_6->setLayoutDirection(Qt::RightToLeft);
        Info_6->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_3 = new QLabel(BackUP);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(-30, 144, 240, 30));
        QFont font3;
        font3.setPointSize(8);
        font3.setBold(false);
        font3.setWeight(50);
        label_3->setFont(font3);
        label_3->setLineWidth(0);
        label_3->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        Info = new QLabel(BackUP);
        Info->setObjectName(QStringLiteral("Info"));
        Info->setGeometry(QRect(80, 36, 90, 30));
        Info->setFont(font1);
        Info->setLayoutDirection(Qt::RightToLeft);
        Info->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        Info_5 = new QLabel(BackUP);
        Info_5->setObjectName(QStringLiteral("Info_5"));
        Info_5->setGeometry(QRect(177, 101, 60, 30));
        Info_5->setFont(font1);
        Info_5->setLayoutDirection(Qt::RightToLeft);
        Info_5->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        Details = new QPushButton(BackUP);
        Details->setObjectName(QStringLiteral("Details"));
        Details->setEnabled(true);
        Details->setGeometry(QRect(340, 210, 140, 50));
        QFont font4;
        font4.setPointSize(9);
        font4.setBold(false);
        font4.setWeight(50);
        Details->setFont(font4);
        BackUP_NOW = new QPushButton(BackUP);
        BackUP_NOW->setObjectName(QStringLiteral("BackUP_NOW"));
        BackUP_NOW->setEnabled(true);
        BackUP_NOW->setGeometry(QRect(490, 210, 400, 50));
        QFont font5;
        font5.setPointSize(9);
        font5.setBold(true);
        font5.setWeight(75);
        BackUP_NOW->setFont(font5);
        Info_2 = new QLabel(BackUP);
        Info_2->setObjectName(QStringLiteral("Info_2"));
        Info_2->setGeometry(QRect(80, 101, 90, 30));
        Info_2->setFont(font1);
        Info_2->setLayoutDirection(Qt::RightToLeft);
        Info_2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label = new QLabel(BackUP);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(-30, 14, 240, 30));
        QFont font6;
        font6.setPointSize(8);
        font6.setBold(false);
        font6.setWeight(50);
        font6.setKerning(true);
        label->setFont(font6);
        label->setFrameShape(QFrame::NoFrame);
        label->setFrameShadow(QFrame::Plain);
        label->setLineWidth(0);
        label->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        progressBar = new QProgressBar(BackUP);
        progressBar->setObjectName(QStringLiteral("progressBar"));
        progressBar->setGeometry(QRect(10, 10, 880, 60));
        progressBar->setFont(font2);
        progressBar->setValue(100);
        progressBar->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        progressBar->setOrientation(Qt::Horizontal);
        progressBar_3 = new QProgressBar(BackUP);
        progressBar_3->setObjectName(QStringLiteral("progressBar_3"));
        progressBar_3->setGeometry(QRect(10, 140, 880, 60));
        progressBar_3->setFont(font2);
        progressBar_3->setValue(0);
        Info_3 = new QLabel(BackUP);
        Info_3->setObjectName(QStringLiteral("Info_3"));
        Info_3->setGeometry(QRect(80, 166, 90, 30));
        Info_3->setFont(font1);
        Info_3->setLayoutDirection(Qt::RightToLeft);
        Info_3->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_2 = new QLabel(BackUP);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(-30, 79, 240, 30));
        label_2->setFont(font3);
        label_2->setLineWidth(0);
        label_2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        Unmount = new QPushButton(BackUP);
        Unmount->setObjectName(QStringLiteral("Unmount"));
        Unmount->setEnabled(false);
        Unmount->setGeometry(QRect(200, 210, 130, 50));
        Unmount->setFont(font4);
        Unmount->setStyleSheet(QStringLiteral(""));
        Mount = new QPushButton(BackUP);
        Mount->setObjectName(QStringLiteral("Mount"));
        Mount->setEnabled(true);
        Mount->setGeometry(QRect(10, 210, 180, 50));
        Mount->setFont(font4);
        openMount = new QPushButton(BackUP);
        openMount->setObjectName(QStringLiteral("openMount"));
        openMount->setEnabled(true);
        openMount->setGeometry(QRect(10, -200, 180, 50));
        openMount->setFont(font5);
        openMount->setStyleSheet(QStringLiteral("background:#0000AA; color:#FFFFFF;"));
        tabWidget->addTab(BackUP, QString());
        progressBar->raise();
        progressBar_3->raise();
        progressBar_2->raise();
        Info_4->raise();
        Info_6->raise();
        label_3->raise();
        Info->raise();
        Info_5->raise();
        Details->raise();
        BackUP_NOW->raise();
        Info_2->raise();
        label->raise();
        Info_3->raise();
        label_2->raise();
        Unmount->raise();
        Mount->raise();
        openMount->raise();
        Configuration = new QWidget();
        Configuration->setObjectName(QStringLiteral("Configuration"));
        pathInfo_5 = new QLabel(Configuration);
        pathInfo_5->setObjectName(QStringLiteral("pathInfo_5"));
        pathInfo_5->setGeometry(QRect(10, 73, 430, 30));
        pathInfo_5->setFont(font);
        pathInfo_6 = new QLabel(Configuration);
        pathInfo_6->setObjectName(QStringLiteral("pathInfo_6"));
        pathInfo_6->setGeometry(QRect(460, 6, 430, 30));
        pathInfo_6->setFont(font);
        pathInfo_7 = new QLabel(Configuration);
        pathInfo_7->setObjectName(QStringLiteral("pathInfo_7"));
        pathInfo_7->setGeometry(QRect(10, 140, 270, 30));
        pathInfo_7->setFont(font);
        pathInfo_8 = new QLabel(Configuration);
        pathInfo_8->setObjectName(QStringLiteral("pathInfo_8"));
        pathInfo_8->setGeometry(QRect(460, 73, 430, 30));
        pathInfo_8->setFont(font);
        pathInfo_9 = new QLabel(Configuration);
        pathInfo_9->setObjectName(QStringLiteral("pathInfo_9"));
        pathInfo_9->setGeometry(QRect(300, 140, 590, 30));
        pathInfo_9->setFont(font);
        Config_File = new QPushButton(Configuration);
        Config_File->setObjectName(QStringLiteral("Config_File"));
        Config_File->setEnabled(true);
        Config_File->setGeometry(QRect(10, 210, 880, 50));
        Config_File->setFont(font5);
        pathInfo_2 = new QLineEdit(Configuration);
        pathInfo_2->setObjectName(QStringLiteral("pathInfo_2"));
        pathInfo_2->setGeometry(QRect(10, 103, 430, 30));
        QFont font7;
        font7.setPointSize(8);
        pathInfo_2->setFont(font7);
        pathInfo_2->setStyleSheet(QStringLiteral("background:#555; color:#FFFFFF; margin-top: -2px;"));
        pathInfo_2->setReadOnly(true);
        pathInfo = new QLineEdit(Configuration);
        pathInfo->setObjectName(QStringLiteral("pathInfo"));
        pathInfo->setEnabled(false);
        pathInfo->setGeometry(QRect(10, 170, 270, 30));
        pathInfo->setFont(font7);
        pathInfo->setStyleSheet(QStringLiteral("background:#999; color:#DDDDDD; margin-top: -2px;"));
        pathInfo->setReadOnly(true);
        pathInfo_3 = new QLineEdit(Configuration);
        pathInfo_3->setObjectName(QStringLiteral("pathInfo_3"));
        pathInfo_3->setGeometry(QRect(460, 103, 430, 30));
        pathInfo_3->setFont(font7);
        pathInfo_3->setStyleSheet(QStringLiteral("background:#555; color:#FFFFFF; margin-top: -2px;"));
        pathInfo_3->setReadOnly(true);
        pathInfo_4 = new QLineEdit(Configuration);
        pathInfo_4->setObjectName(QStringLiteral("pathInfo_4"));
        pathInfo_4->setGeometry(QRect(460, 36, 430, 30));
        pathInfo_4->setFont(font7);
        pathInfo_4->setStyleSheet(QStringLiteral("background:#555; color:#FFFFFF; margin-top: -2px;"));
        pathInfo_4->setReadOnly(true);
        pathInfo_10 = new QLineEdit(Configuration);
        pathInfo_10->setObjectName(QStringLiteral("pathInfo_10"));
        pathInfo_10->setEnabled(false);
        pathInfo_10->setGeometry(QRect(300, 170, 590, 30));
        pathInfo_10->setFont(font7);
        pathInfo_10->setStyleSheet(QStringLiteral("background:#999; color:#DDDDDD; margin-top: -2px;"));
        pathInfo_10->setReadOnly(true);
        pathInfo_11 = new QLineEdit(Configuration);
        pathInfo_11->setObjectName(QStringLiteral("pathInfo_11"));
        pathInfo_11->setGeometry(QRect(10, 36, 430, 30));
        pathInfo_11->setFont(font7);
        pathInfo_11->setStyleSheet(QStringLiteral("background:#555; color:#FFFFFF; margin-top: -2px;"));
        pathInfo_11->setReadOnly(true);
        pathInfo_12 = new QLabel(Configuration);
        pathInfo_12->setObjectName(QStringLiteral("pathInfo_12"));
        pathInfo_12->setGeometry(QRect(10, 6, 430, 30));
        pathInfo_12->setFont(font);
        tabWidget->addTab(Configuration, QString());
        Delete = new QWidget();
        Delete->setObjectName(QStringLiteral("Delete"));
        listWidget = new QListWidget(Delete);
        listWidget->setObjectName(QStringLiteral("listWidget"));
        listWidget->setGeometry(QRect(10, 10, 330, 250));
        listWidget->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        textBrowser = new QTextBrowser(Delete);
        textBrowser->setObjectName(QStringLiteral("textBrowser"));
        textBrowser->setGeometry(QRect(350, 10, 550, 110));
        textBrowser->setFrameShape(QFrame::NoFrame);
        textBrowser->setFrameShadow(QFrame::Raised);
        textBrowser->setLineWidth(0);
        textBrowser->setMidLineWidth(0);
        textBrowser->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        textBrowser->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        DELETE = new QPushButton(Delete);
        DELETE->setObjectName(QStringLiteral("DELETE"));
        DELETE->setEnabled(false);
        DELETE->setGeometry(QRect(670, 200, 210, 50));
        DELETE->setFont(font5);
        Check_Delete = new QLabel(Delete);
        Check_Delete->setObjectName(QStringLiteral("Check_Delete"));
        Check_Delete->setGeometry(QRect(360, 200, 140, 50));
        QFont font8;
        font8.setPointSize(10);
        Check_Delete->setFont(font8);
        Check_Delete->setAlignment(Qt::AlignCenter);
        Re_Check_Delete = new QLineEdit(Delete);
        Re_Check_Delete->setObjectName(QStringLiteral("Re_Check_Delete"));
        Re_Check_Delete->setGeometry(QRect(520, 200, 140, 50));
        Re_Check_Delete->setFont(font8);
        Re_Check_Delete->setAlignment(Qt::AlignCenter);
        label_4 = new QLabel(Delete);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(358, 150, 520, 34));
        label_4->setFont(font7);
        frame = new QFrame(Delete);
        frame->setObjectName(QStringLiteral("frame"));
        frame->setGeometry(QRect(350, 190, 540, 70));
        frame->setFrameShape(QFrame::WinPanel);
        frame->setFrameShadow(QFrame::Sunken);
        frame->setLineWidth(2);
        tabWidget->addTab(Delete, QString());
        frame->raise();
        listWidget->raise();
        textBrowser->raise();
        DELETE->raise();
        Check_Delete->raise();
        Re_Check_Delete->raise();
        label_4->raise();
        Schedule = new QWidget();
        Schedule->setObjectName(QStringLiteral("Schedule"));
        HH = new QTimeEdit(Schedule);
        HH->setObjectName(QStringLiteral("HH"));
        HH->setGeometry(QRect(730, 150, 80, 40));
        HH->setAlignment(Qt::AlignCenter);
        HH->setMaximumTime(QTime(23, 59, 59));
        HH->setTime(QTime(0, 0, 0));
        WD3 = new QCheckBox(Schedule);
        WD3->setObjectName(QStringLiteral("WD3"));
        WD3->setGeometry(QRect(190, 150, 80, 40));
        QFont font9;
        font9.setBold(true);
        font9.setWeight(75);
        WD3->setFont(font9);
        WD3->setTristate(false);
        WD4 = new QCheckBox(Schedule);
        WD4->setObjectName(QStringLiteral("WD4"));
        WD4->setGeometry(QRect(280, 150, 80, 40));
        WD4->setFont(font9);
        WD4->setTristate(false);
        WD7 = new QCheckBox(Schedule);
        WD7->setObjectName(QStringLiteral("WD7"));
        WD7->setGeometry(QRect(550, 150, 80, 40));
        WD7->setFont(font9);
        WD7->setTristate(false);
        WD5 = new QCheckBox(Schedule);
        WD5->setObjectName(QStringLiteral("WD5"));
        WD5->setGeometry(QRect(370, 150, 80, 40));
        WD5->setFont(font9);
        WD5->setTristate(false);
        WD6 = new QCheckBox(Schedule);
        WD6->setObjectName(QStringLiteral("WD6"));
        WD6->setGeometry(QRect(460, 150, 80, 40));
        WD6->setFont(font9);
        WD6->setTristate(false);
        WD2 = new QCheckBox(Schedule);
        WD2->setObjectName(QStringLiteral("WD2"));
        WD2->setGeometry(QRect(100, 150, 80, 40));
        WD2->setFont(font9);
        WD2->setTristate(false);
        WD1 = new QCheckBox(Schedule);
        WD1->setObjectName(QStringLiteral("WD1"));
        WD1->setGeometry(QRect(10, 150, 80, 40));
        WD1->setFont(font9);
        WD1->setStyleSheet(QStringLiteral(""));
        WD1->setTristate(false);
        label_5 = new QLabel(Schedule);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(20, 100, 180, 30));
        QFont font10;
        font10.setPointSize(9);
        label_5->setFont(font10);
        label_6 = new QLabel(Schedule);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(660, 100, 90, 34));
        label_6->setFont(font10);
        line_4 = new QFrame(Schedule);
        line_4->setObjectName(QStringLiteral("line_4"));
        line_4->setGeometry(QRect(-40, 140, 950, 4));
        line_4->setFrameShadow(QFrame::Sunken);
        line_4->setLineWidth(2);
        line_4->setMidLineWidth(2);
        line_4->setFrameShape(QFrame::HLine);
        Remove = new QPushButton(Schedule);
        Remove->setObjectName(QStringLiteral("Remove"));
        Remove->setEnabled(false);
        Remove->setGeometry(QRect(500, 210, 190, 50));
        Remove->setFont(font5);
        AddChange = new QPushButton(Schedule);
        AddChange->setObjectName(QStringLiteral("AddChange"));
        AddChange->setEnabled(true);
        AddChange->setGeometry(QRect(700, 210, 190, 50));
        AddChange->setFont(font5);
        Time24AMPM = new QComboBox(Schedule);
        Time24AMPM->addItem(QString());
        Time24AMPM->addItem(QString());
        Time24AMPM->addItem(QString());
        Time24AMPM->setObjectName(QStringLiteral("Time24AMPM"));
        Time24AMPM->setGeometry(QRect(650, 150, 80, 40));
        label_7 = new QLabel(Schedule);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(20, 20, 650, 34));
        label_7->setFont(font8);
        mm = new QTimeEdit(Schedule);
        mm->setObjectName(QStringLiteral("mm"));
        mm->setGeometry(QRect(810, 150, 80, 40));
        mm->setAlignment(Qt::AlignCenter);
        label_8 = new QLabel(Schedule);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(20, 50, 870, 34));
        QFont font11;
        font11.setPointSize(10);
        font11.setBold(false);
        font11.setWeight(50);
        label_8->setFont(font11);
        tabWidget->addTab(Schedule, QString());
        WD3->raise();
        WD4->raise();
        HH->raise();
        WD7->raise();
        WD5->raise();
        WD6->raise();
        WD2->raise();
        WD1->raise();
        label_5->raise();
        label_6->raise();
        line_4->raise();
        Remove->raise();
        AddChange->raise();
        Time24AMPM->raise();
        label_7->raise();
        mm->raise();
        label_8->raise();
        wait = new QLabel(Main);
        wait->setObjectName(QStringLiteral("wait"));
        wait->setGeometry(QRect(-30, -520, 980, 440));
        QFont font12;
        font12.setPointSize(16);
        font12.setBold(true);
        font12.setWeight(75);
        wait->setFont(font12);
        wait->setStyleSheet(QLatin1String("background-color: rgba(0, 0, 0, 200);\n"
"color:#FFFFFF;"));
        wait->setLocale(QLocale(QLocale::English, QLocale::UnitedStates));
        wait->setAlignment(Qt::AlignCenter);
        BORG = new QPushButton(Main);
        BORG->setObjectName(QStringLiteral("BORG"));
        BORG->setGeometry(QRect(640, 12, 275, 50));
        loadBAR_2 = new QProgressBar(Main);
        loadBAR_2->setObjectName(QStringLiteral("loadBAR_2"));
        loadBAR_2->setGeometry(QRect(-10, -150, 940, 20));
        loadBAR_2->setLayoutDirection(Qt::LeftToRight);
        loadBAR_2->setValue(50);
        loadBAR = new QProgressBar(Main);
        loadBAR->setObjectName(QStringLiteral("loadBAR"));
        loadBAR->setGeometry(QRect(-10, -160, 940, 10));
        loadBAR->setLayoutDirection(Qt::LeftToRight);
        loadBAR->setValue(50);
        loadBAR_3 = new QProgressBar(Main);
        loadBAR_3->setObjectName(QStringLiteral("loadBAR_3"));
        loadBAR_3->setGeometry(QRect(-10, -130, 940, 10));
        loadBAR_3->setLayoutDirection(Qt::LeftToRight);
        loadBAR_3->setValue(50);
        BORG_BackUP_GUI->setCentralWidget(Main);
        tabWidget->raise();
        BORG->raise();
        wait->raise();
        loadBAR->raise();
        loadBAR_2->raise();
        loadBAR_3->raise();
        menuBar = new QMenuBar(BORG_BackUP_GUI);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 925, 39));
        menuFile = new QMenu(menuBar);
        menuFile->setObjectName(QStringLiteral("menuFile"));
        menuHelp = new QMenu(menuBar);
        menuHelp->setObjectName(QStringLiteral("menuHelp"));
        menuActions = new QMenu(menuBar);
        menuActions->setObjectName(QStringLiteral("menuActions"));
        BORG_BackUP_GUI->setMenuBar(menuBar);

        menuBar->addAction(menuFile->menuAction());
        menuBar->addAction(menuActions->menuAction());
        menuBar->addAction(menuHelp->menuAction());
        menuFile->addAction(Exit);
        menuHelp->addAction(Borg_Homepage_Menu);
        menuHelp->addAction(Tutorial_Menu);
        menuHelp->addAction(About_Menu);
        menuActions->addAction(Create_a_new_BackUP_point_Menu);
        menuActions->addSeparator();
        menuActions->addAction(Mount_Menu);
        menuActions->addAction(Unmount_Menu);
        menuActions->addSeparator();
        menuActions->addAction(Details_Menu);
        menuActions->addSeparator();
        menuActions->addAction(Configuration_Menu);
        menuActions->addAction(Delete_Section_Menu);
        menuActions->addAction(Schedule_Section_Menu);

        retranslateUi(BORG_BackUP_GUI);

        tabWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(BORG_BackUP_GUI);
    } // setupUi

    void retranslateUi(QMainWindow *BORG_BackUP_GUI)
    {
        BORG_BackUP_GUI->setWindowTitle(QApplication::translate("BORG_BackUP_GUI", "BORG_BackUP_GUI", nullptr));
        actionMount->setText(QApplication::translate("BORG_BackUP_GUI", "&Mount", nullptr));
        actionUnmount->setText(QApplication::translate("BORG_BackUP_GUI", "&Unmount", nullptr));
        actionmore_Details->setText(QApplication::translate("BORG_BackUP_GUI", "more &Details", nullptr));
        actionBackUP_NOW->setText(QApplication::translate("BORG_BackUP_GUI", "&BackUP NOW", nullptr));
        actionExit->setText(QApplication::translate("BORG_BackUP_GUI", "&Exit", nullptr));
        actionAbout->setText(QApplication::translate("BORG_BackUP_GUI", "&About", nullptr));
        New->setText(QApplication::translate("BORG_BackUP_GUI", "&New", nullptr));
        About_Menu->setText(QApplication::translate("BORG_BackUP_GUI", "&About", nullptr));
        Exit->setText(QApplication::translate("BORG_BackUP_GUI", "&Exit", nullptr));
        Create_a_new_BackUP_point_Menu->setText(QApplication::translate("BORG_BackUP_GUI", "&Create a new BackUP point", nullptr));
        Mount_Menu->setText(QApplication::translate("BORG_BackUP_GUI", "&Mount", nullptr));
        Unmount_Menu->setText(QApplication::translate("BORG_BackUP_GUI", "&Unmount", nullptr));
        Details_Menu->setText(QApplication::translate("BORG_BackUP_GUI", "&all Details", nullptr));
        actionDelete->setText(QApplication::translate("BORG_BackUP_GUI", "Delete Section", nullptr));
        Schedule_Section_Menu->setText(QApplication::translate("BORG_BackUP_GUI", "&Schedule Section", nullptr));
        Delete_Section_Menu->setText(QApplication::translate("BORG_BackUP_GUI", "&Delete Section", nullptr));
        Configuration_Menu->setText(QApplication::translate("BORG_BackUP_GUI", "C&onfiguration", nullptr));
        Borg_Homepage_Menu->setText(QApplication::translate("BORG_BackUP_GUI", "&Borg Homepage", nullptr));
        Tutorial_Menu->setText(QApplication::translate("BORG_BackUP_GUI", "&Tutorial", nullptr));
        Info_4->setText(QString());
        Info_6->setText(QString());
        label_3->setText(QApplication::translate("BORG_BackUP_GUI", "Deduplicated size", nullptr));
        Info->setText(QString());
        Info_5->setText(QString());
        Details->setText(QApplication::translate("BORG_BackUP_GUI", "all Details", nullptr));
        BackUP_NOW->setText(QApplication::translate("BORG_BackUP_GUI", "Create a new BackUP point", nullptr));
        Info_2->setText(QString());
        label->setText(QApplication::translate("BORG_BackUP_GUI", "Original size", nullptr));
        Info_3->setText(QString());
        label_2->setText(QApplication::translate("BORG_BackUP_GUI", "Compressed size", nullptr));
        Unmount->setText(QApplication::translate("BORG_BackUP_GUI", "Unmount", nullptr));
        Mount->setText(QApplication::translate("BORG_BackUP_GUI", "Mount", nullptr));
        openMount->setText(QApplication::translate("BORG_BackUP_GUI", "Open Mount", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(BackUP), QApplication::translate("BORG_BackUP_GUI", "BackUP", nullptr));
        pathInfo_5->setText(QApplication::translate("BORG_BackUP_GUI", "BackUP Path:", nullptr));
        pathInfo_6->setText(QApplication::translate("BORG_BackUP_GUI", "Mount Folder:", nullptr));
        pathInfo_7->setText(QApplication::translate("BORG_BackUP_GUI", "User Directory:", nullptr));
        pathInfo_8->setText(QApplication::translate("BORG_BackUP_GUI", "BackUP Name:", nullptr));
        pathInfo_9->setText(QApplication::translate("BORG_BackUP_GUI", "Application Directory Path:", nullptr));
        Config_File->setText(QApplication::translate("BORG_BackUP_GUI", "Opening the configuration file", nullptr));
        pathInfo_12->setText(QApplication::translate("BORG_BackUP_GUI", "BackUP Parameters", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(Configuration), QApplication::translate("BORG_BackUP_GUI", "Configuration", nullptr));
        textBrowser->setHtml(QApplication::translate("BORG_BackUP_GUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Droid Sans Thai'; font-size:8pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:5px; margin-left:5px; margin-right:5px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Here you can delete partial backups.<br /></span><span style=\" font-size:9pt; font-weight:400;\">In general, you should never delete the most recent part of the backup!</span></p></body></html>", nullptr));
        DELETE->setText(QApplication::translate("BORG_BackUP_GUI", "DELETE", nullptr));
        Check_Delete->setText(QString());
        label_4->setText(QApplication::translate("BORG_BackUP_GUI", "Deletion confirmation code", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(Delete), QApplication::translate("BORG_BackUP_GUI", "Delete", nullptr));
        HH->setDisplayFormat(QApplication::translate("BORG_BackUP_GUI", "HH", nullptr));
        WD3->setText(QApplication::translate("BORG_BackUP_GUI", "We", nullptr));
        WD4->setText(QApplication::translate("BORG_BackUP_GUI", "Th", nullptr));
        WD7->setText(QApplication::translate("BORG_BackUP_GUI", "Su", nullptr));
        WD5->setText(QApplication::translate("BORG_BackUP_GUI", "Fr", nullptr));
        WD6->setText(QApplication::translate("BORG_BackUP_GUI", "Sa", nullptr));
        WD2->setText(QApplication::translate("BORG_BackUP_GUI", "Tu", nullptr));
        WD1->setText(QApplication::translate("BORG_BackUP_GUI", "Mo", nullptr));
        label_5->setText(QApplication::translate("BORG_BackUP_GUI", "Weekdays", nullptr));
        label_6->setText(QApplication::translate("BORG_BackUP_GUI", "Time", nullptr));
        Remove->setText(QApplication::translate("BORG_BackUP_GUI", "Remove", nullptr));
        AddChange->setText(QApplication::translate("BORG_BackUP_GUI", "Add", nullptr));
        Time24AMPM->setItemText(0, QApplication::translate("BORG_BackUP_GUI", "24", nullptr));
        Time24AMPM->setItemText(1, QApplication::translate("BORG_BackUP_GUI", "AM", nullptr));
        Time24AMPM->setItemText(2, QApplication::translate("BORG_BackUP_GUI", "PM", nullptr));

        label_7->setText(QApplication::translate("BORG_BackUP_GUI", "Create a schedule for an automatic BackUP", nullptr));
        mm->setDisplayFormat(QApplication::translate("BORG_BackUP_GUI", "mm", nullptr));
        label_8->setText(QApplication::translate("BORG_BackUP_GUI", "The Cron Deamon must also be active on the system!", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(Schedule), QApplication::translate("BORG_BackUP_GUI", "Schedule", nullptr));
        wait->setText(QApplication::translate("BORG_BackUP_GUI", "Mission is in progress, please wait!", nullptr));
        BORG->setText(QString());
        loadBAR_2->setFormat(QString());
        loadBAR->setFormat(QString());
        loadBAR_3->setFormat(QString());
        menuFile->setTitle(QApplication::translate("BORG_BackUP_GUI", "Fi&le", nullptr));
        menuHelp->setTitle(QApplication::translate("BORG_BackUP_GUI", "Hel&p", nullptr));
        menuActions->setTitle(QApplication::translate("BORG_BackUP_GUI", "Ac&tions", nullptr));
    } // retranslateUi

};

namespace Ui {
    class BORG_BackUP_GUI: public Ui_BORG_BackUP_GUI {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_BORG_BACKUP_GUI_H
